language.Add("sc_npc_alyx", "[SC] Alyx")
language.Add("sc_npc_antlion", "[SC] Antlion")
language.Add("sc_npc_antlion_worker", "[SC] Antlion Worker")
language.Add("sc_npc_antlionguard", "[SC] Antlion Guard")
language.Add("sc_npc_barney", "[SC] Barney")
language.Add("sc_npc_citizen", "[SC] Citizen")
language.Add("sc_npc_clawscanner", "[SC] Claw Scanner")
language.Add("sc_npc_combine", "[SC] Combine")
language.Add("sc_npc_combine_s", "[SC] Combine Soldier")
language.Add("sc_npc_cscanner", "[SC] City Scanner")
language.Add("sc_npc_fastzombie", "[SC] Fast Zombie")
language.Add("sc_npc_fastzombie_torso", "[SC] Fast Zombie Torso")
language.Add("sc_npc_headcrab", "[SC] Headcrab")
language.Add("sc_npc_headcrab_black", "[SC] Poison Headcrab")
language.Add("sc_npc_headcrab_fast", "[SC] Fast Headcrab")
language.Add("sc_npc_headcrab_poison", "[SC] Poison Headcrab")
language.Add("sc_npc_hunter", "[SC] Hunter")
language.Add("sc_npc_manhack", "[SC] Manhack")
language.Add("sc_npc_metropolice", "[SC] Metro-Police")
language.Add("sc_npc_monk", "[SC] Father Grigori")
language.Add("sc_npc_poisonzombie", "[SC] Poison Zombie")
language.Add("sc_npc_rollermine", "[SC] Rollermine")
language.Add("sc_npc_zombie", "[SC] Zombie")
language.Add("sc_npc_zombie_torso", "[SC] Zombie Torso")
language.Add("sc_npc_zombine", "[SC] Zombine")
